function [Markers]=Marker_setTrunkSpinePOSSUP(~)
% Definition of the markers set used in the M2S
%
%   INPUT
%   - nb_markers_hand: number of markers used on each hand
%   OUTPUT
%   - Markers: set of markers (see the Documentation for the structure) 
%________________________________________________________
%
% Licence
% Toolbox distributed under GPL 3.0 Licence
%________________________________________________________
%
% Authors : Antoine Muller, Charles Pontonnier, Pierre Puchaud and
% Georges Dumont
%________________________________________________________
%% Comit 2025, authors: Minh Nguyen, Aurélien Schuster, Aurélie Tomezzoli
% Virtual markers corresponding to the posterosuperior corners of the vertebrae are used 
% to drive the kinematic model, as if they were skin markers. 
%
% Before running the analysis in CUSTOM, you MUST compute the predicted vertebral 
% positions using the regressions available here:
% Tomezzoli, A., A. Agouram, B. Chalamet, et al. ‘Predicting Cervico-Thoraco-Lumbar 
% Vertebra Positions from Cutaneous Markers: Combining Local Frame and Postural 
% Predictors Improves Robustness to Posture’. Journal of Biomechanics 164 (February 2024): 
% 111961. https://doi.org/10.1016/j.jbiomech.2024.111961.
% 
% With this markerset, you MUST use simultaneously these model parts:
% - UpperTrunkCervical_KinRhythm + LowerTrunk_KinRhythm + Skull    OR
% - UpperTrunkCervical_Limits    + LowerTrunk_Limits   + Skull.m  OR 
% - UpperTrunkCervical_NoLimits  + LowerTrunk_NoLimits + Skull.m


s=cell(0);
s=[s;{
      'STRN' 'STRN' {'On';'On';'Off'};...
      'CLAV' 'CLAV' {'On';'On';'Off'};...
      'T12POSSUP' 'T12POSSUP' {'Off';'On';'On'};...
      'T11POSSUP' 'T11POSSUP' {'Off';'On';'On'};...
      'T10POSSUP' 'T10POSSUP' {'Off';'Off';'Off'};...
      'T9POSSUP' 'T9POSSUP' {'Off';'Off';'Off'};...
      'T8POSSUP' 'T8POSSUP' {'Off';'Off';'Off'};...
      'T7POSSUP' 'T7POSSUP' {'Off';'Off';'Off'};...
      'T6POSSUP' 'T6POSSUP' {'Off';'Off';'Off'};...
      'T5POSSUP' 'T5POSSUP' {'Off';'Off';'Off'};...
      'T4POSSUP' 'T4POSSUP' {'Off';'Off';'Off'};...
      'T3POSSUP' 'T3POSSUP' {'Off';'Off';'Off'};...
      'T2POSSUP' 'T2POSSUP' {'Off';'Off';'Off'};...
      'T1POSSUP' 'T1POSSUP' {'Off';'Off';'Off'};...
      'L5POSSUP' 'L5POSSUP' {'Off';'Off';'Off'};...
      'L4POSSUP' 'L4POSSUP' {'Off';'Off';'Off'};...
      'L3POSSUP' 'L3POSSUP' {'Off';'Off';'Off'};...
      'L2POSSUP' 'L2POSSUP' {'Off';'Off';'Off'};...
      'L1POSSUP' 'L1POSSUP' {'Off';'Off';'Off'};...
      'C7POSSUP' 'C7POSSUP' {'Off';'Off';'Off'};...
      'C6POSSUP' 'C6POSSUP' {'Off';'Off';'Off'};...
      'C5POSSUP' 'C5POSSUP' {'Off';'Off';'Off'};...
      'C4POSSUP' 'C4POSSUP' {'Off';'Off';'Off'};...
      'C3POSSUP' 'C3POSSUP' {'Off';'Off';'Off'};...
      'C2POSSUP' 'C2POSSUP' {'Off';'Off';'Off'};...
      'C1POSSUP' 'C1POSSUP' {'Off';'Off';'Off'};...
      'RSHO' 'RSHO' {'On';'Off';'On'};...
      'LSHO' 'LSHO' {'On';'Off';'On'};...
      'SkOP' 'SkOP' {'Off';'Off';'Off'};...
      'SkNA' 'SkNA' {'Off';'Off';'Off'};...
      'RSkM' 'RSkM' {'Off';'Off';'Off'};...
      'LSkM' 'LSkM' {'Off';'Off';'Off'};...
      'RFWT' 'RFWT' {'Off';'Off';'Off'};...
      'LFWT' 'LFWT' {'Off';'Off';'Off'};...
      'RBWT' 'RBWT' {'Off';'Off';'Off'};...
      'LBWT' 'LBWT' {'Off';'Off';'Off'}}];...
     

Side={'R';'L'};
%% Leg
%{
for i=1:2
    Signe=Side{i};
    s=[s;{[Signe 'KNE'] [Signe 'KNE'] {'Off';'On';'Off'};[Signe 'ANE'] [Signe 'ANE'] {'Off';'On';'Off'};[Signe 'ANI'] [Signe 'ANI'] {'Off';'Off';'Off'};...
        [Signe 'KNI'] [Signe 'KNI'] {'Off';'On';'On'};[Signe 'HEE'] [Signe 'HEE'] {'Off';'On';'Off'};[Signe 'TAR'] [Signe 'TAR'] {'Off';'On';'On'};...
        [Signe 'TOE'] [Signe 'TOE'] {'Off';'Off';'On'};...
        [Signe 'TARI'] [Signe 'TARI'] {'Off';'On';'On'}}];
end
%}

%{
for i=1:2
    Signe=Side{i};
    s=[s;{[Signe 'KNE'] [Signe 'KNE'] {'Off';'On';'Off'};[Signe 'ANE'] [Signe 'ANE'] {'Off';'On';'Off'};[Signe 'ANI'] [Signe 'ANI'] {'Off';'Off';'Off'};...
        [Signe 'KNI'] ['CondylusMedialis' Signe 'Thigh'] {'Off';'On';'On'};[Signe 'HEE'] [Signe 'HEE'] {'Off';'On';'Off'};[Signe 'TAR'] [Signe 'TAR'] {'Off';'On';'On'};...
        [Signe 'TOE'] [Signe 'TOE'] {'Off';'Off';'On'};...
        [Signe 'TARI'] [Signe 'TARI'] {'Off';'On';'On'}}];
         }]; %#ok<AGROW>
end
%}

%% Arm
%{
% for i=1:2
%     Signe=Side{i};
%     s=[s;{[Signe 'HUM'] [Signe 'HUM'] {'Off';'Off';'Off'};[Signe 'RAD'] [Signe 'RAD'] {'On';'On';'Off'};...
%         [Signe 'WRA'] [Signe 'WRA'] {'Off';'Off';'Off'};[Signe 'WRB'] [Signe 'WRB'] {'Off';'On';'Off'}}]; %#ok<AGROW>
%     eval(['s=Hand_markers_' num2str(nb_markers_hand) '(s,Signe);'])
% end
%}

%{
for i=1:2
    Signe=Side{i};
    s=[s;{[Signe 'HUM'] [Signe 'HUM'] {'Off';'On';'Off'};[Signe 'RAD'] [Signe 'RAD'] {'On';'On';'Off'};...
        [Signe 'WRA'] [Signe 'WRA'] {'Off';'Off';'Off'};[Signe 'WRB'] [Signe 'WRB'] {'Off';'Off';'Off'};
        [Signe 'CAR'] [Signe 'CAR1'] {'Off';'Off';'Off'}}]; %#ok<AGROW>
    % eval(['s=Hand_markers_' num2str(nb_markers_hand) '(s,Signe);'])
end
%}

Markers=struct('name',{s{:,1}}','anat_position',{s{:,2}}','calib_dir',{s{:,3}}'); %#ok<CCAT1>

end

% function [s]=Hand_markers_1(s,Signe)   %#ok<DEFNU>
% % 1 marker on the hand
%     %s=[s;{[Signe 'CAR'] [Signe 'CAR1'] {'Off';'Off';'Off'}}];   
% end
% function [s]=Hand_markers_2(s,Signe)   %#ok<DEFNU>  
% % 2 markers on the hand
%     % s=[s;{[Signe 'CAR'] [Signe 'CAR2'] {'Off';'Off';'Off'};[Signe 'OHAND'] [Signe 'OHAND'] {'Off';'Off';'Off'}}];    
% end    
% function [s]=Hand_markers_3(s,Signe)   %#ok<DEFNU>  
% % 3 markers on the hand
%     % s=[s;{[Signe 'CAR'] [Signe 'CAR3'] {'Off';'Off';'Off'};[Signe 'IDX3'] [Signe 'IDX3'] {'Off';'Off';'Off'};[Signe 'PNK3'] [Signe 'PNK3'] {'Off';'Off';'Off'}}];    
% end