function [Markers]=Marker_setTrunkSpine(~)
% Definition of the markers set used in the M2S
%
%   INPUT
%   - nb_markers_hand: number of markers used on each hand
%   OUTPUT
%   - Markers: set of markers (see the Documentation for the structure) 
%________________________________________________________
%
% Licence
% Toolbox distributed under GPL 3.0 Licence
%________________________________________________________
%
% Authors : Antoine Muller, Charles Pontonnier, Pierre Puchaud and
% Georges Dumont
%________________________________________________________
s=cell(0);
s=[s;{
      'STRN' 'STRN' {'On';'On';'Off'};...
      'CLAV' 'CLAV' {'On';'On';'Off'};...
      'T12' 'T12' {'Off';'Off';'Off'};...
      'T11' 'T11' {'Off';'Off';'Off'};...
      'T10' 'T10' {'Off';'Off';'Off'};...
      'T9' 'T9' {'Off';'Off';'Off'};...
      'T8' 'T8' {'Off';'Off';'Off'};...
      'T7' 'T7' {'Off';'Off';'Off'};...
      'T6' 'T6' {'Off';'Off';'Off'};...
      'T5' 'T5' {'Off';'Off';'Off'};...
      'T4' 'T4' {'Off';'Off';'Off'};...
      'T3' 'T3' {'Off';'Off';'Off'};...
      'T2' 'T2' {'Off';'Off';'Off'};...
      'T1' 'T1' {'Off';'Off';'Off'};...
      'L5' 'L5' {'Off';'Off';'Off'};...
      'L4' 'L4' {'Off';'Off';'Off'};...
      'L3' 'L3' {'Off';'Off';'Off'};...
      'L2' 'L2' {'Off';'Off';'Off'};...
      'L1' 'L1' {'Off';'Off';'Off'};...
      'C7' 'C7' {'Off';'Off';'Off'};...
      'C6' 'C6' {'Off';'Off';'Off'};...
      'C5' 'C5' {'Off';'Off';'Off'};...
      'C4' 'C4' {'Off';'Off';'Off'};...
      'C3' 'C3' {'Off';'Off';'Off'};...
      'C2' 'C2' {'Off';'Off';'Off'};...
      'C1' 'C1' {'Off';'Off';'Off'};...
      'RSHO' 'RSHO' {'Off';'Off';'Off'};...
      'LSHO' 'LSHO' {'Off';'Off';'Off'};...
      'SkOP' 'SkOP' {'Off';'Off';'Off'};...
      'SkNA' 'SkNA' {'Off';'Off';'Off'};...
      'RSkM' 'RSkM' {'Off';'Off';'Off'};...
      'LSkM' 'LSkM' {'Off';'Off';'Off'};...
      'RFWT' 'RFWT' {'Off';'Off';'Off'};...
      'LFWT' 'LFWT' {'Off';'Off';'Off'};...
      'RBWT' 'RBWT' {'Off';'Off';'Off'};...
      'LBWT' 'LBWT' {'Off';'Off';'Off'}}];...
      
Side={'R';'L'};


%% Leg
%
for i=1:2
    Signe=Side{i};
    s=[s;{[Signe 'KNE'] [Signe 'KNE'] {'Off';'On';'Off'};[Signe 'ANE'] [Signe 'ANE'] {'Off';'On';'Off'};[Signe 'ANI'] [Signe 'ANI'] {'Off';'Off';'Off'};...
        [Signe 'KNI'] [Signe 'KNI'] {'Off';'On';'On'};[Signe 'HEE'] [Signe 'HEE'] {'Off';'On';'Off'};[Signe 'TAR'] [Signe 'TAR'] {'Off';'On';'On'};...
        [Signe 'TOE'] [Signe 'TOE'] {'Off';'Off';'On'};...
        [Signe 'TARI'] [Signe 'TARI'] {'Off';'On';'On'}}];
end
%}


% for i=1:2
%     Signe=Side{i};
%     s=[s;{[Signe 'KNE'] [Signe 'KNE'] {'Off';'On';'Off'};[Signe 'ANE'] [Signe 'ANE'] {'Off';'On';'Off'};[Signe 'ANI'] [Signe 'ANI'] {'Off';'Off';'Off'};...
%         [Signe 'KNI'] ['CondylusMedialis' Signe 'Thigh'] {'Off';'On';'On'};[Signe 'HEE'] [Signe 'HEE'] {'Off';'On';'Off'};[Signe 'TAR'] [Signe 'TAR'] {'Off';'On';'On'};...
%         [Signe 'TOE'] [Signe 'TOE'] {'Off';'Off';'On'};...
%         [Signe 'TARI'] [Signe 'TARI'] {'Off';'On';'On'}}];
% %         }]; %#ok<AGROW>
% end


%% Arm
% for i=1:2
%     Signe=Side{i};
%     s=[s;{[Signe 'HUM'] [Signe 'HUM'] {'Off';'Off';'Off'};[Signe 'RAD'] [Signe 'RAD'] {'On';'On';'Off'};...
%         [Signe 'WRA'] [Signe 'WRA'] {'Off';'Off';'Off'};[Signe 'WRB'] [Signe 'WRB'] {'Off';'On';'Off'}}]; %#ok<AGROW>
%     eval(['s=Hand_markers_' num2str(nb_markers_hand) '(s,Signe);'])
% end

%{
for i=1:2
    Signe=Side{i};
    s=[s;{[Signe 'HUM'] [Signe 'HUM'] {'Off';'On';'Off'};[Signe 'RAD'] [Signe 'RAD'] {'On';'On';'Off'};...
        [Signe 'WRA'] [Signe 'WRA'] {'Off';'Off';'Off'};[Signe 'WRB'] [Signe 'WRB'] {'Off';'Off';'Off'};
        [Signe 'CAR'] [Signe 'CAR1'] {'Off';'Off';'Off'}}]; %#ok<AGROW>
    % eval(['s=Hand_markers_' num2str(nb_markers_hand) '(s,Signe);'])
end
%}

Markers=struct('name',{s{:,1}}','anat_position',{s{:,2}}','calib_dir',{s{:,3}}'); %#ok<CCAT1>

end

% function [s]=Hand_markers_1(s,Signe)   %#ok<DEFNU>
% % 1 marker on the hand
%     %s=[s;{[Signe 'CAR'] [Signe 'CAR1'] {'Off';'Off';'Off'}}];   
% end
% function [s]=Hand_markers_2(s,Signe)   %#ok<DEFNU>  
% % 2 markers on the hand
%     % s=[s;{[Signe 'CAR'] [Signe 'CAR2'] {'Off';'Off';'Off'};[Signe 'OHAND'] [Signe 'OHAND'] {'Off';'Off';'Off'}}];    
% end    
% function [s]=Hand_markers_3(s,Signe)   %#ok<DEFNU>  
% % 3 markers on the hand
%     % s=[s;{[Signe 'CAR'] [Signe 'CAR3'] {'Off';'Off';'Off'};[Signe 'IDX3'] [Signe 'IDX3'] {'Off';'Off';'Off'};[Signe 'PNK3'] [Signe 'PNK3'] {'Off';'Off';'Off'}}];    
% end